pref("extensions.resetKiosk.timeoutseconds", 60);
pref("extensions.resetKiosk.forceFullscreen", false);
pref("extensions.resetKiosk.noNavBar", false);
pref("extensions.resetKiosk.stayFullscreen", false);
pref("extensions.resetKiosk.reuseExisting",false);
pref("browser.tabs.warnOnClose",false);
pref("network.manage-offline-status",false);
pref("extensions.resetKiosk.clearHistory",false);
pref("extensions.resetKiosk.clearCookies",false);
pref("extensions.resetKiosk.clearCache",false);
pref("extensions.resetKiosk.disableContextMenu",false);
